### ISSUE TITLE
missing $ inserted

### ISSUE THREAD

**Issue by gil-l** [samfcmc/ist-dissertation-latex-template#13]
When I try to build I get errors like the title in the cover page. It always happens after a medium space. I researched a bit and it seems \: is supposed to be used in math mode and by surrounding all of these with $ the problem appears fixed. I didn't submit a PR with this fix yet because these medium spaces have been there since Oct 4 and no one else mentioned this problem. Is there another way to clear these errors? Is it a version/platform (I'm using texlive on debian) localized problem?

**Comment by samfcmc** [comment]
How are you trying to build?

**Comment by gil-l** [comment]
I looked some more into it and it seems to be a texlive package version problem. I found out I was using the wheezy repo version, updated to the latest and it works. Problem solved :) Sorry for bothering. Maybe there could be a reminder in the readme to always use the latest versions.
I'm using the Makefile if it's still relevant.
