### ISSUE TITLE
Acronyms page missing

### ISSUE THREAD

**Issue by mvpgomes** [samfcmc/ist-dissertation-latex-template#3]

**Comment by mvpgomes** [comment]
In the current version it is only possible to generate the acronyms if you have a complete Latex installation, in OS X there is another way to do that, and in Windows .... well fuck Windows ... if you are a serious developer you shouldn't use that shit xD.

**Comment by samfcmc** [comment]
I have checked your commit on this. I have MacTex installed but in the compiled document there are no glossaries at all

**Comment by samfcmc** [comment]
By the way... Some users (non-developers) can use this. Some of them use windows... Be careful about those kinds of comments xD.
Is the solution on your commit supposed to work on all platforms?

**Comment by mvpgomes** [comment]
It is because in OSX, if you have installed Latex via MacTex, the command makeglossaries is not available to the user. The glossary must be generated via the TexShop GUI (I don't know if there is another way to do this without TexShop).

**Comment by samfcmc** [comment]
I have the command available. Maybe because I added `/usr/texbin` directory to my path.
I tried to run this command the way you put in the `toPDF.sh` script and it returns:

```
➜  meic-dissertation-template git:(master) makeglossaries
makeglossaries: Need exactly one file argument.
Use `makeglossaries --help' for help.
```

The script is not doing it right. I will figure it out...

**Comment by mvpgomes** [comment]
Sorry xD. My bad, you need to pass the filename without the .tex extension to the command. This should fix the script. I fix that.

**Comment by mvpgomes** [comment]
I already fixed the script. Can you test and verify if its all OK?

**Comment by samfcmc** [comment]
Yep that works. Thanks man ;)
